Add tdcmm classes
joon-e/tidycomm pull request #28
Opened 2023-04-01 12:48 UTC by joon-e

This PR adds basic `tdcmm` class, suitable for all output objects, and implements it including subclass `tdcmm-chi2` for the `crosstab()`. Other outputs can then be adapted following the same logic.

2023-04-12 13:52 UTC, MarHai requested changes
Wondering why you would want to merge into master rather than devel?

2023-05-02 11:56 UTC, MarHai approved these changes

2023-05-07 20:24 UTC, LKobilke commented on R/tdcmm_class.R
> +#' @description The `tdcmm` class is a subclass of a [`tbl_df`][tibble::tbl_df],
**_Simplified description:_**
@description The `tdcmm` class is a specialized type of data frame that is a subclass of [`tbl_df`][tibble::tbl_df], also known as a "tibble". It is designed to be used with `tidycomm` functions to provide additional information and context to the output tibbles generated by these functions.

This subclass specifically augments output based on statistical tests, by including the relevant model object(s) estimated during the analysis, as well as any performed assumption checks.

2023-05-08 10:01 UTC, LKobilke requested changes

2023-05-09 07:19 UTC, MarHai commented on R/describe.R
> +      Unique = length(unique(.data$Value)) - ifelse(Missing > 0, 1, 0),
It refers to the row above, that is the just created summarize column `Missing`. 

```r
tribble(~a, ~b,
        1, 'a',
        NA, 'b',
        2, 'a',
        2, NA) %>% 
  describe_cat(b)
```

2023-05-09 14:10 UTC, merged